export const BASE_URL = "https://api.themoviedb.org/3/";
export const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3M2QxZTQwZmUzYzM5YmRmZGNkM2M1ODM4OGRkNTI5MSIsIm5iZiI6MTc4MTgzNjM2Ni41ODgsInN1YiI6IjZhMzRhYTRlOWM4NGQyOTAxNjM4NDlhMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.8xjM_s8QL4DG4rJi8zK7wSTW5gFJeUCzvvyux2rwkrk";
